Separate regression approaches
NorskRegnesentral/shapr pull request #379
Opened 2024-02-22 17:34 UTC by LHBO

In this PR, we add the option to use separate regression models to estimate the contributions functions. 
We use the tidymodels framework which allows the user to choose between 80 models that can easily be tuned via cv by providing a workflow object.

2024-04-03 09:35 UTC, LHBO commented on R/approach_regression_separate.R
> +    current_x_train <- internal$data$x_train[, ..current_comb][, "y_hat" := internal$data$x_train_y_hat]
Agreed to let it be

2024-04-03 09:52 UTC, LHBO commented on R/setup.R
> +        "with only the above strings except the regression approaches."
"`approach` must be one of the following: \n", paste0(supported_approaches, collapse = ", "). "\n",
"These can also be combined (except 'regression_surrogate' and 'regression_separate') by passing a vector of length one less than the number of features (", n_features - 1, ")."

2024-04-03 10:05 UTC, LHBO commented on vignettes/understanding_shapr_regression.Rmd.orig
> +# Either use library(tidymodels) or separately specify the libraries
Use library(tidymodels) (check if work)

2024-04-09 20:45 UTC, LHBO commented on vignettes/understanding_shapr_regression.Rmd.orig
> +We can also focus on the Shapley value explanations for the best 5 methods according to the
Added

2024-04-15 12:08 UTC, martinju requested changes
Looks good. See some comments. I will look at the vignettes (and recompile them) separately.

2024-04-15 12:22 UTC, LHBO commented on python/shaprpy/explain.py
> +        verbose=verbose,
Must have happened when I refactored using Pycharm. It is NOT recommended to have spaces here. Especially, if we want to follow the PEP8 Python standard. See https://peps.python.org/pep-0008/#other-recommendations. This also affects indentations. We will discuss. We need to use same standard in all Python files.

2024-04-15 12:41 UTC, LHBO commented on vignettes/understanding_shapr.Rmd.orig
> +In a separate vignette, we elaborate and demonstrate the regression paradigm.
Added title.

2024-04-15 12:43 UTC, LHBO commented on python/shaprpy/explain.py
PEP 8 standard. I go back to non-standard formatting. We need to determine what to do in the future in another PR.

2024-04-15 12:54 UTC, LHBO commented on python/requirements.txt
> +shaprpy~=0.1
Good point, and I am not sure about this either. I will remove it. Pycharm just came with a pop-up "requirements.txt is missing. Do you want to add it?"

2024-04-16 17:34 UTC, LHBO commented on python/shaprpy/explain.py
> +      # TODO: discuss with martin how to get the descriptions passed here. Because we cannot use @inheritDotParams.
Added this function and updated the python documentation

2024-04-16 18:51 UTC, LHBO commented
Made all alterations requested in the previous review. Have built the vignettes.

2024-04-17 12:47 UTC, martinju approved these changes

2024-04-17 13:42 UTC, merged