Fix R devel notes
NorskRegnesentral/shapr pull request #389
Opened 2024-04-11 12:44 UTC by martinju

Recent updates to R-devel complains about some bugs in our documentation. The PR fixes these bugs

2024-04-11 20:55 UTC, LHBO requested changes
Rather change to `last_state` in the roxygen documentation, as that is where the logical error was.

2024-04-11 20:55 UTC, LHBO commented on R/approach_vaeac.R
> -      parameters = last_state
Would prefer it to be the way it was before, but rather change `last_epoch` to `last_state` in the one line in the roxygen of `vaeac_print_train_summary`. Then no other changes are needed

2024-04-11 20:55 UTC, LHBO commented on man/vaeac_print_train_summary.Rd
> +vaeac_print_train_summary(best_epoch, best_epoch_running, last_epoch)
Rebuild manual after changing back to `last_state` in the function call and rather updating the oxygen @param.

2024-04-12 07:07 UTC, martinju commented on R/approach_vaeac_torch_modules.R
> +    size <- nrow(batch) # Get the number of observations in the batch+
```suggestion
    size <- nrow(batch) # Get the number of observations in the batch
```

2024-04-12 08:09 UTC, LHBO approved these changes
Looks good!

2024-04-12 08:09 UTC, merged